contact_links:
  - name: Have questions or need support?
    url: https://forum.iobroker.net/topic/27050/test-adapter-trashschedule-v1-0-x
    about: Please get in touch on the ioBroker Community Forum!
